apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: mynewdemo-image
  namespace: default
spec:
  tag: yogeshraheja/kpackimage
  serviceAccountName: default
  builder:
    name: my-new-builder
    kind: Builder
  source:
    git:
      url: https://github.com/yogeshraheja/demo-kpack.git
      revision: 36ca5ec0515a62445f5a851c3ae5d889e81875dd
